development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 295854032498-3ho1d2ppr8nn84s85mqk60cgvl9bvkir.apps.googleusercontent.com
  google_client_secret: DvSJdlmkvb5I7JSBtbgyTb50
